heat_template_version: 2013-05-23

description: Multiregion wordpress deployment

parameters:

  key_name:
    type: string
    description : Name of a KeyPair to enable SSH access to the instance

  instance_type:
    type: string
    description: Instance type for web and DB servers
    default: m1.small
    constraints:
      - allowed_values: [m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge]
        description: instance_type must be a valid instance type

  image_id:
    type: string
    description: >
      Name or ID of the image to use for the WordPress server.
      Recommended values are fedora-20.i386 or fedora-20.x86_64;
      get them from http://cloud.fedoraproject.org/fedora-20.i386.qcow2
      or http://cloud.fedoraproject.org/fedora-20.x86_64.qcow2 .
    #default: fedora-20.x86_64
    default: fedora-21-software-config

  db_name:
    type: string
    description: WordPress database name
    default: wordpress
    constraints:
      - length: { min: 1, max: 64 }
        description: db_name must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_name must begin with a letter and contain only alphanumeric
          characters

  db_username:
    type: string
    description: The WordPress database admin account username
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 16 }
        description: db_username must be between 1 and 16 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_username must begin with a letter and contain only alphanumeric
          characters

  db_password:
    type: string
    description: The WordPress database admin account password
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_password must be between 1 and 41 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_password must contain only alphanumeric characters

  db_root_password:
    type: string
    description: Root password for MySQL
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_root_password must be between 1 and 41 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_root_password must contain only alphanumeric characters

resources:
  DBServer:
    type: OS::Heat::Stack
    properties:
      context:
        region_name: EDGE-CG-1
      template: { get_file: nested_dbserver.yaml }
      timeout: 60
      parameters:
        key_name: { get_param: key_name }
        instance_type: { get_param: key_name }
        image_id: { get_param: image_id }
        db_name: { get_param: db_name }
        db_username: { get_param: db_username }
        db_password: { get_param: db_password }
        db_root_password: { get_param: db_root_password }
  WebServer:
    type: OS::Heat::Stack
    properties:
      context:
        region_name: EDGE-MG-1
      template: { get_file: nested_webserver.yaml }
      timeout: 60
      parameters:
        key_name: { get_param: key_name }
        instance_type: { get_param: key_name }
        image_id: { get_param: image_id }
        db_name: { get_param: db_name }
        db_username: { get_param: db_username }
        db_password: { get_param: db_password }
        db_root_password: { get_param: db_root_password }

outputs:
  webserver_ip:
    description: Web Server IP address.
    value: { get_attr: [ WebServer, outputs, public_ip ] }
  dbserver_ip:
    description: DB Server IP address.
    value: { get_attr: [ DBServer, outputs, public_ip ] }
